version: 2

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes: github.com/steipete/blucli

linters:
  disable-all: true
  disable:
    - errcheck
  enable:
    - bodyclose
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

linters-settings: {}

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
